name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Adjust the version as needed
        
    - name: Restore NuGet packages
      run: dotnet restore $(solution)
      
    - name: Build solution
      run: dotnet build $(solution) --configuration $(buildConfiguration)
      
    - name: Test solution
      run: dotnet test $(solution) --configuration $(buildConfiguration)
