name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1' 
        
    - name: Restore NuGet packages
      run: dotnet restore ${{ github.workspace }}/**/*.sln
      
    - name: Build solution
      run: dotnet build ${{ github.workspace }}/**/*.sln --configuration $(buildConfiguration)
      
    - name: Test solution
      run: dotnet test ${{ github.workspace }}/**/*.sln --configuration $(buildConfiguration)
